# Generated by Django 2.2.4 on 2019-08-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monster', '0002_usermonster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermonster',
            old_name='List',
            new_name='list',
        ),
    ]
